// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_riverpod_template/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LoginCredentialsAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LoginCredentialsAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}
