name: Flutter Lint
defaults:
    run:
        working-directory: MobilGarsonFlutter

on:
  pull_request:
    branches: [ "master-dev",]
    paths:
      - 'MobilGarsonFlutter/**'
  push:
    branches: [ "master-dev", "master-v2" ]
    paths:
      - 'MobilGarsonFlutter/**'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
    
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
