name: Flutter Lint

on:
  pull_request:
    branches: [ "main",]

  push:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Temporary fix analyzer
        run:
          echo "Temporary fix analyzer see https://github.com/dart-lang/sdk/issues/60784"
          flutter pub add override:analyzer:7.3.0
          flutter pub add override:analyzer_plugin:0.12.0
          flutter pub add override:custom_lint_visitor:1.0.0+7.1.0
    
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
